; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f429zi]
platform = ststm32
board = nucleo_f429zi
framework = stm32cube
board_build.stm32cube.custom_config_header = yes

build_src_filter =
    +<*>
    -<stm32f4xx_hal_eth_legacy.c>

; Upload via mass storage (drag-drop to NODE_F429ZI)
upload_protocol = mbed

; Build flags
build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F429xx
    -DHSE_VALUE=8000000U

; Monitor settings (for debugging)
monitor_speed = 921600
monitor_port = COM6
